# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# For a detailed guide to building and testing with Python, read the docs:
# https://circleci.com/docs/language-python/ for more details
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test: 
    docker:
      - image: condaforge/mambaforge
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install basic OS pkgs
          command: apt-get update && apt-get -y install curl vim
      - run:
          name: Run Linter (python black)
          command: |
            mamba install black
            black . --check
      - run:
          name: Install env
          no_output_timeout: 30m
          command: |
            mamba env create -f workflow/envs/encode_re2g.yml
      - run:
          name: Run tests
          no_output_timeout: 30m
          command: |
            conda run -n encode_re2g pytest -s -n 4 tests/

workflows:
  my-workflow:
    jobs:
      - build-and-test