
### INPUT
ABC_BIOSAMPLES: "config/config_biosamples_chr22.tsv"

### OUTPUT
results_dir: "results/"

### PARAMS
ABC_DIR_PATH: "ABC"

### Reference Files
gene_TSS500: "reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed"
chr_sizes: "reference/GRCh38_EBV.no_alt.chrom.sizes.tsv"
ubiq_expr_genes: "reference/for_classifier_use_ubiquitous_expression_RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.txt"

# Filling new features into prediction file
crispr_dataset: "reference/EPCrisprBenchmark_ensemble_data_GRCh38.tsv.gz"

# ENCODE E2G
MEGAMAP_HIC_FILE: https://s3.us-central-1.wasabisys.com/aiden-encode-hic-mirror/bifocals_iter2/tissues.hic
epsilon: .01

# Filtering Predictions
include_self_promoter: True


### INTERNAL USE ONLY

# e2g path to prepend to reference and script files
# Only relevant when using e2g as a submodule
E2G_DIR_PATH: ""