# INPUT
gene_TSS500: "resources/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed"
abc_predictions: "resources/EnhancerPredictionsAllPutative.txt.gz"
enhancer_list: "resources/EnhancerList.txt"

# OUTPUT
results_dir: "results/"

