
### INPUT
ABC_BIOSAMPLES: "config/config_biosamples.tsv"

### OUTPUT
results_dir: "results/"


### PARAMS
ABC_DIR_PATH: "ABC"

# gen_new_features
gene_TSS500: "resources/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed"
chr_sizes: "resources/GRCh38_EBV.no_alt.chrom.sizes.tsv"

# Filling new features into prediction file
ubiq_expr_genes: "resources/for_classifier_use_ubiquitous_expression_RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.txt"
feature_config: "config/feature_config.tsv"
crispr_dataset: "resources/EPCrisprBenchmark_ensemble_data_GRCh38.tsv.gz"

# ENCODE E2G
feature_table: 
  ATAC: "/oak/stanford/groups/engreitz/Users/sheth/ENCODE-E2G_v2/data/feature_table/model_scATAC_IGVF.tsv"
  DHS: "/oak/stanford/groups/engreitz/Users/atan5133/ENCODE-E2G/data/feature_table/model_ablation_encode_e2g.tsv"
models_dir:
  ATAC: "/oak/stanford/groups/engreitz/Users/sheth/ENCODE-E2G_v2/models_scATAC_IGVF_filt/K562_cellranger_1/"
  DHS: "/oak/stanford/groups/engreitz/Users/atan5133/ENCODE-E2G/models"
epsilon: .01
threshold: .09

