
# Input config
model_config: "config/config_models_test.tsv"
dataset_config: "config/config_datasets_test.tsv" 
run_feature_analysis: False # do you want to run feature analysis? 

# Output directory
results_dir: "results_test/"

# Reference files
gene_TSS500: "reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed" # TSS reference file
chr_sizes: "reference/GRCh38_EBV.no_alt.chrom.sizes.tsv"
ubiq_expr_genes: "reference/for_classifier_use_ubiquitous_expression_RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.txt"
crispr_dataset: "reference/EPCrisprBenchmark_ensemble_data_GRCh38.tsv.gz" # CRISPR dataset

# Model parameters
epsilon: .01
filter_features: ['ABC.Score', 'ARC'] 
# if any of these features are present, remove CRISPR elements where feature==0 before training
# if more than one are present, elements where any present features==0 will be removed


### INTERNAL USE ONLY
ABC_DIR_PATH: "ABC"
# e2g path to prepend to reference and script files
# Only relevant when using e2g as a submodule
E2G_DIR_PATH: "/oak/stanford/groups/engreitz/Users/sheth/ENCODE_rE2G"