### INPUT
ABC_BIOSAMPLES: "/oak/stanford/groups/engreitz/Users/atan5133/encode_dataset_processing/datasets/biosamples_config_dhs_only.tsv"

### OUTPUT
results_dir: "/oak/stanford/groups/engreitz/Users/atan5133/encode_dataset_processing/results/dhs_only"

# Reference files
gene_TSS500: "reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed"
chr_sizes: "reference/GRCh38_EBV.no_alt.chrom.sizes.tsv"
ubiq_expr_genes: "reference/for_classifier_use_ubiquitous_expression_RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.txt"

# Choosing and applying ENCODE-E2G
MEGAMAP_HIC_FILE: https://s3.us-central-1.wasabisys.com/aiden-encode-hic-mirror/bifocals_iter2/tissues.hic
epsilon: .01

# Filtering predictions
include_self_promoter: True

### INTERNAL USE ONLY
ABC_DIR_PATH: "ABC"
# e2g path to prepend to reference and script files
# Only relevant when using e2g as a submodule
E2G_DIR_PATH: ""
model_dir: "models"
