
# Input config
model_config: "config/config_models_test.tsv"
dataset_config: "config/config_datasets_test.tsv" 
run_feature_analysis: False # do you want to run feature analysis? 

# Output directory
results_dir: "results_test_L1L2/"

# Reference files
gene_TSS500: "reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed" # TSS reference file
chr_sizes: "reference/GRCh38_EBV.no_alt.chrom.sizes.tsv"
ubiq_expr_genes: "reference/for_classifier_use_ubiquitous_expression_RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.txt"
crispr_dataset: "reference/EPCrisprBenchmark_ensemble_data_GRCh38.tsv.gz" # CRISPR dataset

# Model parameters
epsilon: .01
default_params: 
  'solver': 'lbfgs'
  'fit_intercept': True
  'penalty': 'none'
  'max_iter': 1e8
  'class_weight': None
  'tol': 1e-4
  'warm_start': False
  'random_state': 0
  'verbose': True
  'n_jobs': 1

### INTERNAL USE ONLY
ABC_DIR_PATH: "ABC"
# e2g path to prepend to reference and script files
# Only relevant when using e2g as a submodule
E2G_DIR_PATH: "."